name: coverage
channels:
  - defaults
dependencies:
  - python=3.7.10
  - geopandas
  - pandas
  - numpy
  - pip
  pip:
    - scipy
    - skyfield
# prefix: /Users/kevinlalli/miniconda3/envs/coverage
