# from: https://github.com/binder-examples/python-conda_pip/blob/HEAD/environment.yml
name: coverage
channels:
  - defaults
dependencies:
  - python=3.7.10
  - geopandas
  - pandas
  - numpy
  - shapely
  - pip
  - pip:
    - scipy
    - skyfield
# prefix: /Users/kevinlalli/miniconda3/envs/coverage
